#!/usr/bin/env bash

if [ `id -u` -ne 0 ]; then
   echo "You must run as root!"; exit 1
fi

test [ -h /usr/local/opt/sp-gen ] && ln -s $PWD /usr/local/opt/sp-gen
test [ -L /usr/local/bin/sp-gen ] && ln -s $PWD/sp-gen /usr/local/bin/sp-gen
