#!/usr/bin/env bash

PREFIX=/usr/local/opt/sp-gen

if [[ $1 == "-h" || $1 == "--help" ]]; then
    echo "Usage: ./sp-gen [ --template ]"
    exit 0
fi

if [[ $1 == "--template" ]]; then
    cp $PREFIX/input.sh input.sh
    exit 0
fi

source input.sh

export ADMIN_EMAIL
export ADMIN_NAME
export DESCRIPTION_EN
export DESCRIPTION_SE
export DISPLAY_NAME_EN
export DISPLAY_NAME_SE
export INFORMATION_URL_EN
export INFORMATION_URL_SE
export PRIVACY_STATEMENT_URL_EN
export PRIVACY_STATEMENT_URL_SE
export URL

ID=$URL
export ID

if [[ ! -f "sp-key.pem" && ! -f "sp-cert.pem" ]]; then
    $PREFIX/keygen -h $ID
fi

CERT=$(sed '1d;$d'< sp-cert.pem)
export CERT

envsubst < $PREFIX/template.xml > metadata.xml
